Update check syntax
raspie d&b boost

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -231,25 +231,24 @@ jobs:
           set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
           EOF
 
-          - name: Download and Build Boost for ARM64
-            run: |
-
-             BOOST_VERSION=1.83.0
-             BOOST_VERSION_UNDERSCORE=${BOOST_VERSION//./_}
-             BOOST_URL="https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2/download"
-             wget -O boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2 "$BOOST_URL"
-             if ! file boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2 | grep -q 'bzip2 compressed data'; then
-             echo "Downloaded file is not a valid bzip2 archive"; head boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2; exit 1;
-             fi
-             tar -xjf boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2
-             cd boost_${BOOST_VERSION_UNDERSCORE}
-             echo "using gcc : arm : aarch64-linux-gnu-g++ ;" > user-config.jam
-             ./bootstrap.sh || { echo "Bootstrap failed"; exit 1; }
-             ./b2 --user-config=user-config.jam toolset=gcc-arm target-os=linux architecture=arm address-model=64 --prefix=/tmp/boost-arm64 install || { echo "Boost build failed"; exit 1; }
-             cd ..
-             if [ ! -f /tmp/boost-arm64/include/boost/context/posix/stack_traits.hpp ]; then
-             echo "Boost install incomplete"; exit 1;
-             fi
+      - name: Download and Build Boost for ARM64
+        run: |
+           BOOST_VERSION=1.83.0
+           BOOST_VERSION_UNDERSCORE=${BOOST_VERSION//./_}
+           BOOST_URL="https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2/download"
+           wget -O boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2 "$BOOST_URL"
+           if ! file boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2 | grep -q 'bzip2 compressed data'; then
+           echo "Downloaded file is not a valid bzip2 archive"; head boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2; exit 1;
+           fi
+           tar -xjf boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2
+           cd boost_${BOOST_VERSION_UNDERSCORE}
+           echo "using gcc : arm : aarch64-linux-gnu-g++ ;" > user-config.jam
+           ./bootstrap.sh || { echo "Bootstrap failed"; exit 1; }
+           ./b2 --user-config=user-config.jam toolset=gcc-arm target-os=linux architecture=arm address-model=64 --prefix=/tmp/boost-arm64 install || { echo "Boost build failed"; exit 1; }
+           cd ..
+           if [ ! -f /tmp/boost-arm64/include/boost/context/posix/stack_traits.hpp ]; then
+           echo "Boost install incomplete"; exit 1;
+           fi
   
       - name: Patch Boost to fix PTHREAD_STACK_MIN preprocessor issue
         run: |
